import { CaseFieldKey } from "../fieldMeta";

type CaseTemplate = Record<CaseFieldKey, string>;

const TEMPLATES: CaseTemplate[] = [
  {
    id: "",
    title: "Bella the Boxer: Syncope and Exercise Intolerance",
    description: "A 6-year-old female Boxer presents for collapsing episodes during excitement. The owner reports she 'faints' when greeting guests but recovers quickly.",
    species: "Canine",
    patient_name: "Bella",
    patient_age: "6 years",
    patient_sex: "Female (Spayed)",
    condition: "Arrhythmogenic Right Ventricular Cardiomyopathy (ARVC)",
    category: "Cardiology",
    difficulty: "Hard",
    version: "1",
    tags: "cardiology, canine, syncope, arrhythmia",
    is_published: "false",
    estimated_time: "30",
    image_url: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80",
    details: "Presenting Complaint: Syncope.\nDuration: 2 weeks.\nDiet: Commercial dry food.\nCurrent Meds: None.",
    physical_exam_findings: "HR: 160 bpm (irregularly irregular rhythm). RR: 24 bpm. MM: Pink, CRT < 2s. Femoral pulses: Pulse deficits present. Auscultation: Grade 2/6 left apical systolic murmur. Lungs: Clear.",
    diagnostic_findings: "ECG: Ventricular premature complexes (VPCs) in bigeminy, upright in lead II (suggesting LV origin) but some with LBBB morphology (RV origin). Holter recommended. Echo: Mild LA enlargement, otherwise normal function.",
    owner_background: "Role: Owner (Mrs. Thompson).\nPersonality: Anxious but observant. Loves Bella dearly.\nKnowledge: Knows Boxers have 'heart issues' but hopes it's just heat exhaustion.",
    history_feedback: "Ensure you ask about the exact nature of the collapse (flaccid vs rigid), duration, and triggers (excitement vs exercise).",
    owner_follow_up: "Mrs. Thompson asks if Bella needs surgery or just pills, and if she can still play ball.",
    owner_follow_up_feedback: "Did the student explain the prognosis of ARVC? Did they discuss the risk of sudden death gently but clearly?",
    owner_diagnosis: "ARVC (Boxer Cardiomyopathy).",
    get_owner_prompt: "You are Mrs. Thompson. You are worried. Describe the fainting: 'She just drops, her legs go out, she's awake but can't move.'",
    get_history_feedback_prompt: "Evaluate if the student differentiated syncope from seizure based on your description.",
    get_physical_exam_prompt: "Provide the heart rate and rhythm. Mention the pulse deficits if they check pulses while listening.",
    get_diagnostic_prompt: "Reveal the ECG findings: frequent VPCs. If they ask for Troponin, say it is elevated.",
    get_owner_follow_up_prompt: "Ask about quality of life and medication side effects.",
    get_owner_follow_up_feedback_prompt: "Assess the communication of the treatment plan (Sotalol/Mexiletine).",
    get_owner_diagnosis_prompt: "React with concern but relief that there is a treatment.",
    get_overall_feedback_prompt: "Did the student identify the arrhythmia? Did they recommend a Holter? Did they manage the client's anxiety?",
    owner_avatar_url: "",
    nurse_avatar_url: "",
    owner_persona_id: "",
    nurse_persona_id: "",
    findings_release_strategy: "immediate"
  },
  {
    id: "",
    title: "Luna the Siamese: Polyuria and Weight Loss",
    description: "A 12-year-old Siamese cat is brought in for weight loss despite a ravenous appetite. The owner also notes larger clumps in the litter box.",
    species: "Feline",
    patient_name: "Luna",
    patient_age: "12 years",
    patient_sex: "Female (Spayed)",
    condition: "Hyperthyroidism",
    category: "Endocrinology",
    difficulty: "Medium",
    version: "1",
    tags: "feline, endocrinology, geriatric, weight-loss",
    is_published: "false",
    estimated_time: "20",
    image_url: "https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&w=800&q=80",
    details: "Presenting Complaint: Weight loss, PU/PD, polyphagia.\nDuration: 3 months.\nBehavior: More vocal at night, slightly aggressive.",
    physical_exam_findings: "BCS: 3/9. HR: 220 bpm (tachycardia). Palpable thyroid slip on the left side. Coat: Unkempt. Nails: Overgrown.",
    diagnostic_findings: "Total T4: >15 ug/dL (High). CBC/Chem: Mild ALT elevation, otherwise WNL. USG: 1.035.",
    owner_background: "Role: Owner (Mr. Chen).\nPersonality: Practical, slightly annoyed by the night howling.\nConcerns: Thinks it's just 'old age' but the weight loss is scary.",
    history_feedback: "Check if the student asked about behavioral changes (vocalization, aggression) which are classic for hyperthyroid cats.",
    owner_follow_up: "Mr. Chen asks about the options: 'Can we just give a pill? I heard about radioactive stuff.'",
    owner_follow_up_feedback: "Did the student explain the three main options: Methimazole, I-131, and Surgery (or Diet)?",
    owner_diagnosis: "Feline Hyperthyroidism.",
    get_owner_prompt: "You are Mr. Chen. Mention she eats like a horse but looks like a skeleton. Complain about her meowing at 3 AM.",
    get_history_feedback_prompt: "Did they ask about appetite and thirst specifically?",
    get_physical_exam_prompt: "If they palpate the neck, mention they feel a small nodule.",
    get_diagnostic_prompt: "Provide the high T4 result immediately when asked for bloodwork.",
    get_owner_follow_up_prompt: "Ask which treatment is best for a cat that is hard to pill.",
    get_owner_follow_up_feedback_prompt: "Evaluate if the student offered transdermal medication or I-131 as alternatives to pilling.",
    get_owner_diagnosis_prompt: "Be relieved it's treatable. Ask how much it costs.",
    get_overall_feedback_prompt: "Did they catch the thyroid slip? Did they confirm with T4? Did they discuss treatment options clearly?",
    owner_avatar_url: "",
    nurse_avatar_url: "",
    owner_persona_id: "",
    nurse_persona_id: "",
    findings_release_strategy: "immediate"
  },
  {
    id: "",
    title: "Max the Golden: Acute Lameness",
    description: "A 2-year-old male Golden Retriever presents for acute non-weight bearing lameness of the right pelvic limb after playing fetch.",
    species: "Canine",
    patient_name: "Max",
    patient_age: "2 years",
    patient_sex: "Male (Intact)",
    condition: "Cranial Cruciate Ligament (CCL) Rupture",
    category: "Orthopedics",
    difficulty: "Easy",
    version: "1",
    tags: "orthopedics, canine, lameness, trauma",
    is_published: "false",
    estimated_time: "15",
    image_url: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?auto=format&fit=crop&w=800&q=80",
    details: "Presenting Complaint: RPL Lameness.\nOnset: Acute, 2 hours ago.\nActivity: Chasing a ball, yelped and held leg up.",
    physical_exam_findings: "Gait: Grade 4/5 lameness Right Pelvic Limb. Stifle: Positive cranial drawer, positive tibial compression test. Joint effusion palpable. Pain on extension.",
    diagnostic_findings: "Radiographs: Stifle effusion, loss of infrapatellar fat pad detail. No fractures.",
    owner_background: "Role: Owner (Sarah).\nPersonality: Active, worried about sports career (agility).\nConcerns: 'Is it broken? Can he run again?'",
    history_feedback: "Ensure the student asked about the mechanism of injury (traumatic vs chronic).",
    owner_follow_up: "Sarah asks if he needs surgery or if rest is enough.",
    owner_follow_up_feedback: "Did the student explain why conservative management is often insufficient for large breeds?",
    owner_diagnosis: "CCL Rupture.",
    get_owner_prompt: "You are Sarah. You are very upset because Max is your agility partner. Describe the yelp and the limp.",
    get_history_feedback_prompt: "Did they ask if he has had previous limp issues?",
    get_physical_exam_prompt: "If they manipulate the knee, say Max whines and pulls away.",
    get_diagnostic_prompt: "Show the X-rays: effusion but no bone break.",
    get_owner_follow_up_prompt: "Ask about TPLO vs Lateral Suture.",
    get_owner_follow_up_feedback_prompt: "Did they explain the TPLO mechanics simply?",
    get_owner_diagnosis_prompt: "Accept the need for surgery but worry about the recovery time.",
    get_overall_feedback_prompt: "Did they perform an orthopedic exam? Did they diagnose the CCL tear? Did they recommend surgery?",
    owner_avatar_url: "",
    nurse_avatar_url: "",
    owner_persona_id: "",
    nurse_persona_id: "",
    findings_release_strategy: "immediate"
  }
];

export function generateRandomCase(): CaseTemplate {
  const randomIndex = Math.floor(Math.random() * TEMPLATES.length);
  return { ...TEMPLATES[randomIndex] };
}
