import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import { AuthProvider } from "@/features/auth/services/authService";
import { ProtectedRoute } from "@/features/auth/components/protected-route";
import { Navbar } from "@/features/navigation/components/navbar";

const geistSans = GeistSans;

const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {process.env.NEXT_PUBLIC_ENABLE_AUTH_PROTECTION === "true" ? (
            <ProtectedRoute>
              <Navbar />
              <main>{children}</main>
            </ProtectedRoute>
          ) : (
            <>
              <Navbar />
              <main>{children}</main>
            </>
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
