import {
	CHAT_SYSTEM_GUIDELINE_DEFAULT,
	CHAT_SYSTEM_GUIDELINE_PROMPT_ID,
} from "@/features/prompts/defaults/personaPrompts";

export const CHAT_SYSTEM_GUIDELINE = CHAT_SYSTEM_GUIDELINE_DEFAULT;

export {
	CHAT_SYSTEM_GUIDELINE_DEFAULT,
	CHAT_SYSTEM_GUIDELINE_PROMPT_ID,
};
