-- Seed nurse_specializations with species-specific clinical knowledge
-- Run: psql -f scripts/seed-nurse-specializations.sql
-- Or paste into Supabase SQL Editor

-- Clean existing data (use with caution)
-- DELETE FROM public.nurse_specializations;

INSERT INTO public.nurse_specializations (species_key, display_name, image_url, sex, voice_id, behavior_prompt, skills, lab_reference_ranges, vital_reference_ranges, common_pathologies, metadata)
VALUES

-- ============================================================
-- EQUINE NURSE
-- ============================================================
('equine', 'Sarah Mitchell', NULL, 'female', 'nova',
 'You are Sarah Mitchell, an experienced equine veterinary nurse with 12 years of specialisation in horse medicine. You have extensive experience with performance horses, breeding operations, and referral hospital cases. You are calm, efficient, and deeply knowledgeable about equine physiology. You communicate findings precisely and professionally. You are comfortable handling thoroughbreds, Warmbloods, and ponies alike.',
 '[
   {"name": "Equine physical examination", "category": "vitals", "description": "Complete systemic exam including GI auscultation, hoof testing, ophthalmic exam"},
   {"name": "Equine emergency triage", "category": "procedures", "description": "Colic assessment, choke management, hemorrhage control, fracture stabilization"},
   {"name": "Equine anesthesia monitoring", "category": "procedures", "description": "Standing sedation, general anesthesia monitoring, recovery assessment"},
   {"name": "Equine lameness evaluation", "category": "procedures", "description": "Flexion tests, nerve blocks, lunging assessment"},
   {"name": "Equine reproductive assessment", "category": "procedures", "description": "Pregnancy diagnosis, foaling assistance, dystocia management"},
   {"name": "Equine dentistry assistance", "category": "procedures", "description": "Dental charting, rasping assistance, periodontal assessment"},
   {"name": "Equine laboratory sample handling", "category": "lab", "description": "Blood collection (jugular), peritoneal fluid, synovial fluid, BAL"},
   {"name": "Equine wound management", "category": "procedures", "description": "Laceration repair, bandaging techniques, cast application"},
   {"name": "Equine neonatal care", "category": "procedures", "description": "Neonatal resuscitation, IgG testing, sepsis monitoring"},
   {"name": "Equine nutrition counseling", "category": "other", "description": "Body condition scoring, ration formulation, metabolic syndrome management"}
 ]'::jsonb,
 '{
   "PCV": "32–53%",
   "Total Protein": "5.7–7.9 g/dL",
   "WBC": "5.4–14.3 × 10⁹/L",
   "Neutrophils": "2.3–7.5 × 10⁹/L",
   "Lymphocytes": "1.5–5.3 × 10⁹/L",
   "Monocytes": "0–0.6 × 10⁹/L",
   "Platelets": "100–350 × 10⁹/L",
   "Fibrinogen": "1–4 g/L",
   "RBC": "6.8–12.9 × 10¹²/L",
   "Hemoglobin": "11–19 g/dL",
   "MCV": "37–58 fL",
   "MCHC": "31–37 g/dL",
   "Sodium": "132–146 mmol/L",
   "Potassium": "2.4–5.7 mmol/L",
   "Chloride": "94–106 mmol/L",
   "Calcium": "2.8–3.5 mmol/L (total), 1.5–2.1 mmol/L (ionized)",
   "Phosphorus": "0.9–1.8 mmol/L",
   "Magnesium": "0.6–1.0 mmol/L",
   "Glucose": "4.2–7.8 mmol/L (75–140 mg/dL)",
   "BUN": "2.5–8.9 mmol/L (7–25 mg/dL)",
   "Creatinine": "71–159 μmol/L (0.8–1.8 mg/dL)",
   "Total Bilirubin": "3.4–51.3 μmol/L (0.2–3.0 mg/dL)",
   "AST": "160–530 U/L",
   "CK": "80–470 U/L",
   "GGT": "5–24 U/L",
   "GLDH": "0–12 U/L",
   "ALP": "70–220 U/L",
   "SDMA": "< 18 μg/dL",
   "Serum Amyloid A": "< 10 mg/L",
   "Triglycerides": "0.1–0.6 mmol/L",
   "NEFA": "0.04–0.4 mmol/L",
   "BHB": "< 0.1 mmol/L",
   "pH (venous)": "7.32–7.44",
   "pCO2 (venous)": "38–46 mmHg",
   "Lactate": "< 2 mmol/L",
   "TP (peritoneal)": "< 20 g/L",
   "WBC (peritoneal)": "< 5 × 10⁹/L"
 }'::jsonb,
 '{
   "Heart Rate": "28–44 bpm (adult), 60–80 bpm (foal)",
   "Respiratory Rate": "10–16 breaths/min (adult), 20–40 breaths/min (foal)",
   "Temperature": "37.2–38.2°C (99.0–100.8°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Jugular Refill": "< 1 second",
   "Gut Sounds": "Present in all 4 quadrants, borborgymi every 10–20 seconds",
   "Pulse Quality": "Strong, regular, synchronous with heartbeat",
   "Hydration Status": "Skin tent < 2 seconds, PCV/TP within normal limits",
   "Body Condition Score": "1–9 scale, ideal 5–6",
   "Rectal Temperature Variation": "Higher in foals, lower in aged horses, diurnal variation up to 0.5°C",
   "Fecal Output": "6–12 piles per day, formed but not dry",
   "Urine Output": "3–18 L/day (adult 500 kg)",
   "Mean Arterial Pressure": "80–120 mmHg",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Colic (all types: impaction, spasmodic, strangulating, gas)", "Laminitis / Founder", "Strangles (Streptococcus equi)", "Recurrent Airway Obstruction (RAO / Heaves)", "Equine Metabolic Syndrome (EMS)", "PPID (Pituitary Pars Intermedia Dysfunction / Cushing''s)", "Equine Influenza", "Equine Herpesvirus (EHV-1, EHV-4)", "Tetanus", "West Nile Virus", "Equine Infectious Anemia (EIA)", "Thrush and hoof abscesses", "Corneal ulcers and uveitis (ERU)", "Lyme disease", "Botulism", "Equine Degenerative Myeloencephalopathy (EDM)", "Gastric Ulcer Syndrome (EGUS)", "Dorsal Displacement of the Soft Palate (DDSP)", "Exercise-Induced Pulmonary Hemorrhage (EIPH)", "Neonatal Maladjustment Syndrome (NMS / Dummy Foal)"]'::jsonb,
 '{"species_display": "Equine", "years_experience": 12, "specialties": ["emergency", "internal medicine", "lameness"], "typical_workplace": "equine referral hospital"}'::jsonb
),

-- ============================================================
-- BOVINE NURSE
-- ============================================================
('bovine', 'Maria Gonzalez', NULL, 'female', 'nova',
 'You are Maria Gonzalez, a seasoned bovine veterinary nurse with 15 years of experience in dairy and beef cattle operations. You are skilled in herd health management, reproductive technology, and production medicine. You approach cases systematically and understand the economic impact of disease on farming operations. You communicate findings clearly and are comfortable working in field conditions.',
 '[
   {"name": "Bovine physical examination", "category": "vitals", "description": "Complete exam including rectal palpation assessment, rumen motility, body condition scoring (1-5 scale)"},
   {"name": "Bovine reproductive assessment", "category": "procedures", "description": "Pregnancy diagnosis (rectal/US), AI assistance, dystocia management, retained placenta"},
   {"name": "Bovine surgical assistance", "category": "procedures", "description": "LDA/RDA correction, C-section, dehorning, castration"},
   {"name": "Bovine emergency triage", "category": "procedures", "description": "Milk fever, downer cow, bloat, toxic mastitis"},
   {"name": "Mastitis management", "category": "procedures", "description": "CMT testing, milk culture sampling, treatment protocols, SCC monitoring"},
   {"name": "Bovine nutrition assessment", "category": "other", "description": "Ration evaluation, BCS monitoring, transition cow management"},
   {"name": "Herd health programs", "category": "other", "description": "Vaccination protocols, parasite control, biosecurity"},
   {"name": "Bovine laboratory sample handling", "category": "lab", "description": "Blood from tail vein/jugular, milk samples, fecal samples, rumen fluid"},
   {"name": "Calf management", "category": "procedures", "description": "Neonatal care, colostrum management, scours treatment, respiratory disease"},
   {"name": "Bovine lameness evaluation", "category": "procedures", "description": "Locomotion scoring, hoof trimming, digital dermatitis management"}
 ]'::jsonb,
 '{
   "PCV": "24–46%",
   "Total Protein": "6.0–8.5 g/dL",
   "WBC": "4.0–12.0 × 10⁹/L",
   "Neutrophils": "0.6–4.0 × 10⁹/L",
   "Lymphocytes": "2.5–7.5 × 10⁹/L",
   "Monocytes": "0–0.8 × 10⁹/L",
   "Platelets": "200–600 × 10⁹/L",
   "Fibrinogen": "2–7 g/L",
   "RBC": "5.0–10.0 × 10¹²/L",
   "Hemoglobin": "8–15 g/dL",
   "MCV": "40–60 fL",
   "MCHC": "29–35 g/dL",
   "Sodium": "132–145 mmol/L",
   "Potassium": "3.5–5.5 mmol/L",
   "Chloride": "96–110 mmol/L",
   "Calcium": "2.1–2.8 mmol/L (total)",
   "Phosphorus": "1.3–2.6 mmol/L",
   "Magnesium": "0.7–1.2 mmol/L",
   "Glucose": "2.2–4.2 mmol/L (40–75 mg/dL)",
   "BUN": "2.1–7.1 mmol/L (6–20 mg/dL)",
   "Creatinine": "53–124 μmol/L (0.6–1.4 mg/dL)",
   "Total Bilirubin": "0–8.6 μmol/L (0–0.5 mg/dL)",
   "AST": "50–150 U/L",
   "CK": "50–350 U/L",
   "GGT": "5–30 U/L",
   "GLDH": "0–30 U/L",
   "ALP": "40–140 U/L",
   "SDMA": "< 18 μg/dL",
   "Serum Amyloid A": "< 10 mg/L",
   "Haptoglobin": "< 0.5 g/L",
   "NEFA": "0.1–0.5 mmol/L (dry), < 0.4 mmol/L (lactating)"},
   "BHB": "< 1.0 mmol/L (serum), < 1.4 mmol/L (milk)",
   "Triglycerides": "0.05–0.3 mmol/L",
   "pH (venous)": "7.31–7.43",
   "Lactate": "< 2 mmol/L",
   "Somatic Cell Count": "< 200,000 cells/mL (individual cow), < 100,000 cells/mL (bulk tank)"
 }'::jsonb,
 '{
   "Heart Rate": "60–80 bpm (adult), 100–130 bpm (calf)",
   "Respiratory Rate": "24–36 breaths/min (adult), 20–40 breaths/min (calf)",
   "Temperature": "38.0–39.3°C (100.4–102.7°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Rumen Motility": "1–2 contractions per minute",
   "Body Condition Score": "1–5 scale, ideal 2.5–3.5 (dairy), 3.0 (beef)",
   "Hydration Status": "Skin tent < 2 seconds, sunken eyes indicate > 5% dehydration",
   "Rectal Examination Findings": "Assess rumen fill, pregnancy status, pelvic pathology",
   "Milk Yield": "Breed-dependent, monitor for sudden drops > 20%",
   "Fecal Consistency": "Formed but soft, monitors for diarrhea/scours",
   "Urine pH": "7.0–8.0",
   "Mean Arterial Pressure": "100–140 mmHg",
   "Pulse Quality": "Strong, regular, best palpated at coccygeal artery"
 }'::jsonb,
 '["Mastitis (Staph aureus, E. coli, Streptococcus spp., Mycoplasma)", "Ketosis / Acetonemia (Type I and II)", "Milk Fever (Parturient Hypocalcemia)", "Bovine Respiratory Disease Complex (BRD / Shipping Fever)", "Displaced Abomasum (LDA/RDA)", "Retained Placenta / Metritis", "Bovine Viral Diarrhea (BVD)", "Infectious Bovine Rhinotracheitis (IBR)", "Johne''s Disease (Paratuberculosis)", "Foot Rot and Digital Dermatitis", "Hardware Disease (Traumatic Reticuloperitonitis)", "Bloat (Frothy and Free-gas)", "Calf Scours (E. coli, Rotavirus, Coronavirus, Cryptosporidium)", "Leptospirosis", "Neosporosis", "Salmonellosis", "Listeriosis", "Anaplasmosis", "Theileriosis (Tropical)", "Fatty Liver Syndrome"]'::jsonb,
 '{"species_display": "Bovine", "years_experience": 15, "specialties": ["dairy production", "reproduction", "mastitis"], "typical_workplace": "dairy and beef operations"}'::jsonb
),

-- ============================================================
-- CANINE NURSE
-- ============================================================
('canine', 'James O''Brien', NULL, 'male', 'echo',
 'You are James O''Brien, a dedicated small animal veterinary nurse with 8 years of experience specializing in canine medicine. You have worked in general practice and emergency referral. You are thorough, compassionate, and skilled at putting anxious dogs (and their owners) at ease. You provide precise clinical observations and are proficient in critical care monitoring. You understand breed-specific conditions and predispositions.',
 '[
   {"name": "Canine physical examination", "category": "vitals", "description": "Complete systemic exam including orthopedic assessment, dental charting, body condition scoring (1-9)"},
   {"name": "Canine emergency triage", "category": "procedures", "description": "GDV stabilization, hemorrhagic gastroenteritis, anaphylaxis, CPR"},
   {"name": "Canine surgical assistance", "category": "procedures", "description": "Pre-operative preparation, intra-operative monitoring, post-operative care"},
   {"name": "Canine anesthesia monitoring", "category": "procedures", "description": "Pre-anesthetic assessment, multi-parameter monitoring, recovery assessment"},
   {"name": "Canine critical care", "category": "procedures", "description": "IV fluid therapy, blood transfusion, oxygen therapy, pain management"},
   {"name": "Canine dental procedures", "category": "procedures", "description": "Dental charting, scaling, polishing, dental radiography assistance"},
   {"name": "Canine laboratory sample handling", "category": "lab", "description": "Cephalic/jugular venipuncture, urinalysis, skin scrapings, FNAs"},
   {"name": "Canine radiography assistance", "category": "procedures", "description": "Positioning, exposure settings, safety protocols"},
   {"name": "Canine behavior assessment", "category": "other", "description": "Fear-free handling, behavior modification, anxiety management"},
   {"name": "Canine rehabilitation", "category": "procedures", "description": "Post-operative physiotherapy, hydrotherapy assistance, laser therapy"}
 ]'::jsonb,
 '{
   "PCV": "37–55%",
   "Total Protein": "5.5–7.5 g/dL",
   "WBC": "5.5–16.9 × 10⁹/L",
   "Neutrophils": "2.0–10.0 × 10⁹/L",
   "Lymphocytes": "0.7–4.8 × 10⁹/L",
   "Monocytes": "0.1–1.4 × 10⁹/L",
   "Eosinophils": "0–1.3 × 10⁹/L",
   "Platelets": "200–500 × 10⁹/L",
   "RBC": "5.5–8.5 × 10¹²/L",
   "Hemoglobin": "12–18 g/dL",
   "MCV": "60–77 fL",
   "MCHC": "32–36 g/dL",
   "Sodium": "139–153 mmol/L",
   "Potassium": "3.6–5.5 mmol/L",
   "Chloride": "102–120 mmol/L",
   "Calcium": "2.3–3.0 mmol/L (total)",
   "Phosphorus": "0.8–2.0 mmol/L",
   "Magnesium": "0.7–1.1 mmol/L",
   "Glucose": "3.9–7.1 mmol/L (70–128 mg/dL)",
   "BUN": "2.5–9.6 mmol/L (7–27 mg/dL)",
   "Creatinine": "44–159 μmol/L (0.5–1.8 mg/dL)",
   "ALT": "10–125 U/L",
   "AST": "10–55 U/L",
   "ALP": "10–150 U/L (adult), up to 300 U/L (growing)",
   "GGT": "0–10 U/L",
   "Total Bilirubin": "0–8.6 μmol/L (0–0.5 mg/dL)",
   "Albumin": "25–37 g/L",
   "Cholesterol": "3.4–9.0 mmol/L",
   "Triglycerides": "0.3–1.5 mmol/L",
   "Amylase": "250–1500 U/L",
   "Lipase": "20–400 U/L",
   "SDMA": "< 18 μg/dL",
   "cPLI": "< 200 μg/L (normal)",
   "NT-proBNP": "< 900 pmol/L",
   "pH (venous)": "7.33–7.45",
   "Lactate": "< 2.5 mmol/L",
   "Coagulation PT": "7–11 seconds",
   "Coagulation aPTT": "12–18 seconds"
 }'::jsonb,
 '{
   "Heart Rate": "80–120 bpm (small breed), 60–100 bpm (large breed), 60–80 bpm (giant breed)",
   "Respiratory Rate": "10–30 breaths/min (at rest)",
   "Temperature": "38.0–39.2°C (100.4–102.5°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Pulse Quality": "Strong, regular, synchronous with heartbeat, palpable at femoral artery",
   "Hydration Status": "Skin tent < 1.5 seconds, moist mucous membranes",
   "Body Condition Score": "1–9 scale, ideal 4–5",
   "Pupil Response": "Bilateral, equal, responsive to light",
   "Gum Color": "Pink (pale = anemia/shock, yellow = icterus, brick-red = sepsis)",
   "Thoracic Auscultation": "Clear lung sounds bilaterally, no murmur or arrhythmia",
   "Abdominal Palpation": "Non-painful, no masses, no organomegaly",
   "Rectal Temperature Variation": "Slightly elevated with stress or exercise",
   "Urine Specific Gravity": "1.015–1.045 (dog on normal diet)",
   "SPO2": "> 95%",
   "Mean Arterial Pressure": "90–130 mmHg"
 }'::jsonb,
 '["Parvoviral Enteritis", "Gastric Dilatation-Volvulus (GDV / Bloat)", "Hyperadrenocorticism (Cushing''s Syndrome)", "Hypoadrenocorticism (Addison''s Disease)", "Diabetes Mellitus", "Chronic Kidney Disease (CKD)", "Acute Pancreatitis", "Intervertebral Disc Disease (IVDD)", "Hip Dysplasia", "Cruciate Ligament Rupture (CCL)", "Otitis Externa", "Atopic Dermatitis", "Hemangiosarcoma", "Lymphoma", "Osteosarcoma", "Mast Cell Tumor", "Heartworm Disease (Dirofilaria immitis)", "Leptospirosis", "Kennel Cough (CIRD Complex)", "Ehrlichiosis and Anaplasmosis", "Patellar Luxation", "Brachycephalic Obstructive Airway Syndrome (BOAS)"]'::jsonb,
 '{"species_display": "Canine", "years_experience": 8, "specialties": ["emergency", "critical care", "surgery"], "typical_workplace": "small animal referral hospital"}'::jsonb
),

-- ============================================================
-- FELINE NURSE
-- ============================================================
('feline', 'Emily Chen', NULL, 'female', 'shimmer',
 'You are Emily Chen, a specialist feline veterinary nurse with 10 years of experience dedicated exclusively to cat medicine. You are a Certified Feline Friendly Nurse with advanced skills in low-stress handling and feline behavior. You understand that cats are not small dogs — they have unique physiology, metabolism, and disease patterns. You are patient, gentle, and expert at reading feline body language. You communicate findings with precision and advocate for feline-specific approaches.',
 '[
   {"name": "Feline physical examination", "category": "vitals", "description": "Gentle systemic exam respecting feline stress thresholds, body condition scoring (1-9), muscle condition score"},
   {"name": "Feline emergency triage", "category": "procedures", "description": "Urethral obstruction, aortic thromboembolism, dyspnea assessment, status epilepticus"},
   {"name": "Feline anesthesia monitoring", "category": "procedures", "description": "Feline-specific drug protocols, thermoregulation, blood pressure management"},
   {"name": "Feline critical care", "category": "procedures", "description": "IV catheterization (difficult in cats), fluid therapy, nasogastric feeding, blood transfusion"},
   {"name": "Feline blood collection", "category": "lab", "description": "Cephalic, jugular, medial saphenous venipuncture, minimal-stress techniques"},
   {"name": "Feline urinary management", "category": "procedures", "description": "Urethral catheterization, urine collection (cystocentesis), FLUTD management"},
   {"name": "Feline dental procedures", "category": "procedures", "description": "Feline dental charting, FORL detection, stomatitis assessment"},
   {"name": "Feline behavior assessment", "category": "other", "description": "Stress scoring, environmental enrichment, feline-friendly handling"},
   {"name": "Feline nutrition counseling", "category": "other", "description": "Life-stage nutrition, obesity management, hepatic lipidosis prevention"},
   {"name": "Feline geriatric care", "category": "procedures", "description": "Quality of life assessment, chronic disease monitoring, pain scoring"}
 ]'::jsonb,
 '{
   "PCV": "30–45%",
   "Total Protein": "5.7–8.0 g/dL",
   "WBC": "3.5–16.0 × 10⁹/L",
   "Neutrophils": "2.5–12.5 × 10⁹/L",
   "Lymphocytes": "1.0–7.0 × 10⁹/L",
   "Monocytes": "0–0.9 × 10⁹/L",
   "Eosinophils": "0–1.5 × 10⁹/L",
   "Platelets": "180–500 × 10⁹/L",
   "RBC": "5.0–10.0 × 10¹²/L",
   "Hemoglobin": "9–15 g/dL",
   "MCV": "39–55 fL",
   "MCHC": "30–36 g/dL",
   "Sodium": "145–158 mmol/L",
   "Potassium": "3.5–5.5 mmol/L",
   "Chloride": "110–128 mmol/L",
   "Calcium": "2.0–2.7 mmol/L (total)",
   "Phosphorus": "0.9–2.3 mmol/L",
   "Magnesium": "0.7–1.1 mmol/L",
   "Glucose": "3.9–8.3 mmol/L (70–150 mg/dL) — note: stress hyperglycemia common",
   "BUN": "5.0–11.0 mmol/L (14–31 mg/dL)",
   "Creatinine": "70–160 μmol/L (0.8–1.8 mg/dL)",
   "ALT": "12–130 U/L",
   "AST": "10–55 U/L",
   "ALP": "10–80 U/L",
   "GGT": "0–6 U/L",
   "Total Bilirubin": "0–5.1 μmol/L (0–0.3 mg/dL)",
   "Albumin": "25–37 g/L",
   "Cholesterol": "1.7–5.7 mmol/L",
   "Triglycerides": "0.2–1.2 mmol/L",
   "SDMA": "< 18 μg/dL",
   "fPLI": "< 3.5 μg/L (normal)",
   "Total T4": "12–40 nmol/L",
   "fNT-proBNP": "< 100 pmol/L",
   "pH (venous)": "7.31–7.46",
   "Lactate": "< 2.5 mmol/L",
   "Coagulation PT": "8–12 seconds",
   "Coagulation aPTT": "12–20 seconds",
   "Urine Specific Gravity": "> 1.035 typically (concentrating ability)"
 }'::jsonb,
 '{
   "Heart Rate": "120–160 bpm (adult), 200–260 bpm (kitten)",
   "Respiratory Rate": "20–30 breaths/min (at rest), > 40 = concerning",
   "Temperature": "38.0–39.2°C (100.4–102.5°F), stress can elevate to 39.5°C",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist (pale gums = emergency in cats)",
   "Pulse Quality": "Strong, regular, femoral pulse assessment",
   "Hydration Status": "Skin tent < 1 second, moist mucous membranes — cats dehydrate rapidly",
   "Body Condition Score": "1–9 scale, ideal 4–5",
   "Pupil Response": "Bilateral, equal, responsive — note: cats have vertical slit pupils",
   "Gum Color": "Pink, tongue color also important in cats",
   "Thoracic Auscultation": "Heart: murmurs common and significant in cats, sinus arrhythmia is ABNORMAL in cats (unlike dogs)",
   "Abdominal Palpation": "Kidneys palpable, bladder size assessment, cranial abdominal mass check",
   "Feline-Specific Notes": "Stress hyperglycemia up to 20 mmol/L, fructosamine more reliable; cats hide pain — use validated pain scales",
   "Urine Specific Gravity": "> 1.035 (cats concentrate well, < 1.035 is significant)",
   "SPO2": "> 95%",
   "Mean Arterial Pressure": "100–150 mmHg"
 }'::jsonb,
 '["Feline Lower Urinary Tract Disease (FLUTD / FIC)", "Hyperthyroidism", "Chronic Kidney Disease (CKD)", "Feline Leukemia Virus (FeLV)", "Feline Immunodeficiency Virus (FIV)", "Diabetes Mellitus", "Hepatic Lipidosis", "Inflammatory Bowel Disease (IBD)", "Feline Asthma / Bronchitis", "Hypertrophic Cardiomyopathy (HCM)", "Feline Infectious Peritonitis (FIP)", "Feline Panleukopenia", "Upper Respiratory Infection Complex (URI)", "Dental Disease and FORLs", "Feline Acne", "Urethral Obstruction (tom cats)", "Aortic Thromboembolism (saddle thrombus)", "Small Cell Lymphoma", "Squamous Cell Carcinoma", "Feline Hyperesthesia Syndrome"]'::jsonb,
 '{"species_display": "Feline", "years_experience": 10, "specialties": ["feline medicine", "behavior", "critical care"], "typical_workplace": "feline-only practice", "certifications": ["Certified Feline Friendly Nurse"]}'::jsonb
)

ON CONFLICT (species_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  behavior_prompt = EXCLUDED.behavior_prompt,
  skills = EXCLUDED.skills,
  lab_reference_ranges = EXCLUDED.lab_reference_ranges,
  vital_reference_ranges = EXCLUDED.vital_reference_ranges,
  common_pathologies = EXCLUDED.common_pathologies,
  metadata = EXCLUDED.metadata,
  updated_at = now();
