-- Seed nurse_specializations with species-specific clinical knowledge
-- Run: psql -f scripts/seed-nurse-specializations.sql
-- Or paste into Supabase SQL Editor

-- Clean existing data (use with caution)
-- DELETE FROM public.nurse_specializations;

INSERT INTO public.nurse_specializations (species_key, display_name, image_url, sex, voice_id, behavior_prompt, skills, lab_reference_ranges, vital_reference_ranges, common_pathologies, metadata)
VALUES

-- ============================================================
-- EQUINE NURSE
-- ============================================================
('equine', 'Sarah Mitchell', NULL, 'female', 'nova',
 'You are Sarah Mitchell, an experienced equine veterinary nurse with 12 years of specialisation in horse medicine. You have extensive experience with performance horses, breeding operations, and referral hospital cases. You are calm, efficient, and deeply knowledgeable about equine physiology. You communicate findings precisely and professionally. You are comfortable handling thoroughbreds, Warmbloods, and ponies alike.',
 '[
   {"name": "Equine physical examination", "category": "vitals", "description": "Complete systemic exam including GI auscultation, hoof testing, ophthalmic exam"},
   {"name": "Equine emergency triage", "category": "procedures", "description": "Colic assessment, choke management, hemorrhage control, fracture stabilization"},
   {"name": "Equine anesthesia monitoring", "category": "procedures", "description": "Standing sedation, general anesthesia monitoring, recovery assessment"},
   {"name": "Equine lameness evaluation", "category": "procedures", "description": "Flexion tests, nerve blocks, lunging assessment"},
   {"name": "Equine reproductive assessment", "category": "procedures", "description": "Pregnancy diagnosis, foaling assistance, dystocia management"},
   {"name": "Equine dentistry assistance", "category": "procedures", "description": "Dental charting, rasping assistance, periodontal assessment"},
   {"name": "Equine laboratory sample handling", "category": "lab", "description": "Blood collection (jugular), peritoneal fluid, synovial fluid, BAL"},
   {"name": "Equine wound management", "category": "procedures", "description": "Laceration repair, bandaging techniques, cast application"},
   {"name": "Equine neonatal care", "category": "procedures", "description": "Neonatal resuscitation, IgG testing, sepsis monitoring"},
   {"name": "Equine nutrition counseling", "category": "other", "description": "Body condition scoring, ration formulation, metabolic syndrome management"}
 ]'::jsonb,
 '{
   "PCV": "32–53%",
   "Total Protein": "5.7–7.9 g/dL",
   "WBC": "5.4–14.3 × 10⁹/L",
   "Neutrophils": "2.3–7.5 × 10⁹/L",
   "Lymphocytes": "1.5–5.3 × 10⁹/L",
   "Monocytes": "0–0.6 × 10⁹/L",
   "Platelets": "100–350 × 10⁹/L",
   "Fibrinogen": "1–4 g/L",
   "RBC": "6.8–12.9 × 10¹²/L",
   "Hemoglobin": "11–19 g/dL",
   "MCV": "37–58 fL",
   "MCHC": "31–37 g/dL",
   "Sodium": "132–146 mmol/L",
   "Potassium": "2.4–5.7 mmol/L",
   "Chloride": "94–106 mmol/L",
   "Calcium": "2.8–3.5 mmol/L (total), 1.5–2.1 mmol/L (ionized)",
   "Phosphorus": "0.9–1.8 mmol/L",
   "Magnesium": "0.6–1.0 mmol/L",
   "Glucose": "4.2–7.8 mmol/L (75–140 mg/dL)",
   "BUN": "2.5–8.9 mmol/L (7–25 mg/dL)",
   "Creatinine": "71–159 μmol/L (0.8–1.8 mg/dL)",
   "Total Bilirubin": "3.4–51.3 μmol/L (0.2–3.0 mg/dL)",
   "AST": "160–530 U/L",
   "CK": "80–470 U/L",
   "GGT": "5–24 U/L",
   "GLDH": "0–12 U/L",
   "ALP": "70–220 U/L",
   "SDMA": "< 18 μg/dL",
   "Serum Amyloid A": "< 10 mg/L",
   "Triglycerides": "0.1–0.6 mmol/L",
   "NEFA": "0.04–0.4 mmol/L",
   "BHB": "< 0.1 mmol/L",
   "pH (venous)": "7.32–7.44",
   "pCO2 (venous)": "38–46 mmHg",
   "Lactate": "< 2 mmol/L",
   "TP (peritoneal)": "< 20 g/L",
   "WBC (peritoneal)": "< 5 × 10⁹/L"
 }'::jsonb,
 '{
   "Heart Rate": "28–44 bpm (adult), 60–80 bpm (foal)",
   "Respiratory Rate": "10–16 breaths/min (adult), 20–40 breaths/min (foal)",
   "Temperature": "37.2–38.2°C (99.0–100.8°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Jugular Refill": "< 1 second",
   "Gut Sounds": "Present in all 4 quadrants, borborgymi every 10–20 seconds",
   "Pulse Quality": "Strong, regular, synchronous with heartbeat",
   "Hydration Status": "Skin tent < 2 seconds, PCV/TP within normal limits",
   "Body Condition Score": "1–9 scale, ideal 5–6",
   "Rectal Temperature Variation": "Higher in foals, lower in aged horses, diurnal variation up to 0.5°C",
   "Fecal Output": "6–12 piles per day, formed but not dry",
   "Urine Output": "3–18 L/day (adult 500 kg)",
   "Mean Arterial Pressure": "80–120 mmHg",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Colic (all types: impaction, spasmodic, strangulating, gas)", "Laminitis / Founder", "Strangles (Streptococcus equi)", "Recurrent Airway Obstruction (RAO / Heaves)", "Equine Metabolic Syndrome (EMS)", "PPID (Pituitary Pars Intermedia Dysfunction / Cushing''s)", "Equine Influenza", "Equine Herpesvirus (EHV-1, EHV-4)", "Tetanus", "West Nile Virus", "Equine Infectious Anemia (EIA)", "Thrush and hoof abscesses", "Corneal ulcers and uveitis (ERU)", "Lyme disease", "Botulism", "Equine Degenerative Myeloencephalopathy (EDM)", "Gastric Ulcer Syndrome (EGUS)", "Dorsal Displacement of the Soft Palate (DDSP)", "Exercise-Induced Pulmonary Hemorrhage (EIPH)", "Neonatal Maladjustment Syndrome (NMS / Dummy Foal)"]'::jsonb,
 '{"species_display": "Equine", "years_experience": 12, "specialties": ["emergency", "internal medicine", "lameness"], "typical_workplace": "equine referral hospital"}'::jsonb
),

-- ============================================================
-- BOVINE NURSE
-- ============================================================
('bovine', 'Maria Gonzalez', NULL, 'female', 'nova',
 'You are Maria Gonzalez, a seasoned bovine veterinary nurse with 15 years of experience in dairy and beef cattle operations. You are skilled in herd health management, reproductive technology, and production medicine. You approach cases systematically and understand the economic impact of disease on farming operations. You communicate findings clearly and are comfortable working in field conditions.',
 '[
   {"name": "Bovine physical examination", "category": "vitals", "description": "Complete exam including rectal palpation assessment, rumen motility, body condition scoring (1-5 scale)"},
   {"name": "Bovine reproductive assessment", "category": "procedures", "description": "Pregnancy diagnosis (rectal/US), AI assistance, dystocia management, retained placenta"},
   {"name": "Bovine surgical assistance", "category": "procedures", "description": "LDA/RDA correction, C-section, dehorning, castration"},
   {"name": "Bovine emergency triage", "category": "procedures", "description": "Milk fever, downer cow, bloat, toxic mastitis"},
   {"name": "Mastitis management", "category": "procedures", "description": "CMT testing, milk culture sampling, treatment protocols, SCC monitoring"},
   {"name": "Bovine nutrition assessment", "category": "other", "description": "Ration evaluation, BCS monitoring, transition cow management"},
   {"name": "Herd health programs", "category": "other", "description": "Vaccination protocols, parasite control, biosecurity"},
   {"name": "Bovine laboratory sample handling", "category": "lab", "description": "Blood from tail vein/jugular, milk samples, fecal samples, rumen fluid"},
   {"name": "Calf management", "category": "procedures", "description": "Neonatal care, colostrum management, scours treatment, respiratory disease"},
   {"name": "Bovine lameness evaluation", "category": "procedures", "description": "Locomotion scoring, hoof trimming, digital dermatitis management"}
 ]'::jsonb,
 '{
   "PCV": "24–46%",
   "Total Protein": "6.0–8.5 g/dL",
   "WBC": "4.0–12.0 × 10⁹/L",
   "Neutrophils": "0.6–4.0 × 10⁹/L",
   "Lymphocytes": "2.5–7.5 × 10⁹/L",
   "Monocytes": "0–0.8 × 10⁹/L",
   "Platelets": "200–600 × 10⁹/L",
   "Fibrinogen": "2–7 g/L",
   "RBC": "5.0–10.0 × 10¹²/L",
   "Hemoglobin": "8–15 g/dL",
   "MCV": "40–60 fL",
   "MCHC": "29–35 g/dL",
   "Sodium": "132–145 mmol/L",
   "Potassium": "3.5–5.5 mmol/L",
   "Chloride": "96–110 mmol/L",
   "Calcium": "2.1–2.8 mmol/L (total)",
   "Phosphorus": "1.3–2.6 mmol/L",
   "Magnesium": "0.7–1.2 mmol/L",
   "Glucose": "2.2–4.2 mmol/L (40–75 mg/dL)",
   "BUN": "2.1–7.1 mmol/L (6–20 mg/dL)",
   "Creatinine": "53–124 μmol/L (0.6–1.4 mg/dL)",
   "Total Bilirubin": "0–8.6 μmol/L (0–0.5 mg/dL)",
   "AST": "50–150 U/L",
   "CK": "50–350 U/L",
   "GGT": "5–30 U/L",
   "GLDH": "0–30 U/L",
   "ALP": "40–140 U/L",
   "SDMA": "< 18 μg/dL",
   "Serum Amyloid A": "< 10 mg/L",
   "Haptoglobin": "< 0.5 g/L",
   "NEFA": "0.1–0.5 mmol/L (dry), < 0.4 mmol/L (lactating)",
   "BHB": "< 1.0 mmol/L (serum), < 1.4 mmol/L (milk)",
   "Triglycerides": "0.05–0.3 mmol/L",
   "pH (venous)": "7.31–7.43",
   "Lactate": "< 2 mmol/L",
   "Somatic Cell Count": "< 200,000 cells/mL (individual cow), < 100,000 cells/mL (bulk tank)"
 }'::jsonb,
 '{
   "Heart Rate": "60–80 bpm (adult), 100–130 bpm (calf)",
   "Respiratory Rate": "24–36 breaths/min (adult), 20–40 breaths/min (calf)",
   "Temperature": "38.0–39.3°C (100.4–102.7°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Rumen Motility": "1–2 contractions per minute",
   "Body Condition Score": "1–5 scale, ideal 2.5–3.5 (dairy), 3.0 (beef)",
   "Hydration Status": "Skin tent < 2 seconds, sunken eyes indicate > 5% dehydration",
   "Rectal Examination Findings": "Assess rumen fill, pregnancy status, pelvic pathology",
   "Milk Yield": "Breed-dependent, monitor for sudden drops > 20%",
   "Fecal Consistency": "Formed but soft, monitors for diarrhea/scours",
   "Urine pH": "7.0–8.0",
   "Mean Arterial Pressure": "100–140 mmHg",
   "Pulse Quality": "Strong, regular, best palpated at coccygeal artery"
 }'::jsonb,
 '["Mastitis (Staph aureus, E. coli, Streptococcus spp., Mycoplasma)", "Ketosis / Acetonemia (Type I and II)", "Milk Fever (Parturient Hypocalcemia)", "Bovine Respiratory Disease Complex (BRD / Shipping Fever)", "Displaced Abomasum (LDA/RDA)", "Retained Placenta / Metritis", "Bovine Viral Diarrhea (BVD)", "Infectious Bovine Rhinotracheitis (IBR)", "Johne''s Disease (Paratuberculosis)", "Foot Rot and Digital Dermatitis", "Hardware Disease (Traumatic Reticuloperitonitis)", "Bloat (Frothy and Free-gas)", "Calf Scours (E. coli, Rotavirus, Coronavirus, Cryptosporidium)", "Leptospirosis", "Neosporosis", "Salmonellosis", "Listeriosis", "Anaplasmosis", "Theileriosis (Tropical)", "Fatty Liver Syndrome"]'::jsonb,
 '{"species_display": "Bovine", "years_experience": 15, "specialties": ["dairy production", "reproduction", "mastitis"], "typical_workplace": "dairy and beef operations"}'::jsonb
),

-- ============================================================
-- CANINE NURSE
-- ============================================================
('canine', 'James O''Brien', NULL, 'male', 'echo',
 'You are James O''Brien, a dedicated small animal veterinary nurse with 8 years of experience specializing in canine medicine. You have worked in general practice and emergency referral. You are thorough, compassionate, and skilled at putting anxious dogs (and their owners) at ease. You provide precise clinical observations and are proficient in critical care monitoring. You understand breed-specific conditions and predispositions.',
 '[
   {"name": "Canine physical examination", "category": "vitals", "description": "Complete systemic exam including orthopedic assessment, dental charting, body condition scoring (1-9)"},
   {"name": "Canine emergency triage", "category": "procedures", "description": "GDV stabilization, hemorrhagic gastroenteritis, anaphylaxis, CPR"},
   {"name": "Canine surgical assistance", "category": "procedures", "description": "Pre-operative preparation, intra-operative monitoring, post-operative care"},
   {"name": "Canine anesthesia monitoring", "category": "procedures", "description": "Pre-anesthetic assessment, multi-parameter monitoring, recovery assessment"},
   {"name": "Canine critical care", "category": "procedures", "description": "IV fluid therapy, blood transfusion, oxygen therapy, pain management"},
   {"name": "Canine dental procedures", "category": "procedures", "description": "Dental charting, scaling, polishing, dental radiography assistance"},
   {"name": "Canine laboratory sample handling", "category": "lab", "description": "Cephalic/jugular venipuncture, urinalysis, skin scrapings, FNAs"},
   {"name": "Canine radiography assistance", "category": "procedures", "description": "Positioning, exposure settings, safety protocols"},
   {"name": "Canine behavior assessment", "category": "other", "description": "Fear-free handling, behavior modification, anxiety management"},
   {"name": "Canine rehabilitation", "category": "procedures", "description": "Post-operative physiotherapy, hydrotherapy assistance, laser therapy"}
 ]'::jsonb,
 '{
   "PCV": "37–55%",
   "Total Protein": "5.5–7.5 g/dL",
   "WBC": "5.5–16.9 × 10⁹/L",
   "Neutrophils": "2.0–10.0 × 10⁹/L",
   "Lymphocytes": "0.7–4.8 × 10⁹/L",
   "Monocytes": "0.1–1.4 × 10⁹/L",
   "Eosinophils": "0–1.3 × 10⁹/L",
   "Platelets": "200–500 × 10⁹/L",
   "RBC": "5.5–8.5 × 10¹²/L",
   "Hemoglobin": "12–18 g/dL",
   "MCV": "60–77 fL",
   "MCHC": "32–36 g/dL",
   "Sodium": "139–153 mmol/L",
   "Potassium": "3.6–5.5 mmol/L",
   "Chloride": "102–120 mmol/L",
   "Calcium": "2.3–3.0 mmol/L (total)",
   "Phosphorus": "0.8–2.0 mmol/L",
   "Magnesium": "0.7–1.1 mmol/L",
   "Glucose": "3.9–7.1 mmol/L (70–128 mg/dL)",
   "BUN": "2.5–9.6 mmol/L (7–27 mg/dL)",
   "Creatinine": "44–159 μmol/L (0.5–1.8 mg/dL)",
   "ALT": "10–125 U/L",
   "AST": "10–55 U/L",
   "ALP": "10–150 U/L (adult), up to 300 U/L (growing)",
   "GGT": "0–10 U/L",
   "Total Bilirubin": "0–8.6 μmol/L (0–0.5 mg/dL)",
   "Albumin": "25–37 g/L",
   "Cholesterol": "3.4–9.0 mmol/L",
   "Triglycerides": "0.3–1.5 mmol/L",
   "Amylase": "250–1500 U/L",
   "Lipase": "20–400 U/L",
   "SDMA": "< 18 μg/dL",
   "cPLI": "< 200 μg/L (normal)",
   "NT-proBNP": "< 900 pmol/L",
   "pH (venous)": "7.33–7.45",
   "Lactate": "< 2.5 mmol/L",
   "Coagulation PT": "7–11 seconds",
   "Coagulation aPTT": "12–18 seconds"
 }'::jsonb,
 '{
   "Heart Rate": "80–120 bpm (small breed), 60–100 bpm (large breed), 60–80 bpm (giant breed)",
   "Respiratory Rate": "10–30 breaths/min (at rest)",
   "Temperature": "38.0–39.2°C (100.4–102.5°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Pulse Quality": "Strong, regular, synchronous with heartbeat, palpable at femoral artery",
   "Hydration Status": "Skin tent < 1.5 seconds, moist mucous membranes",
   "Body Condition Score": "1–9 scale, ideal 4–5",
   "Pupil Response": "Bilateral, equal, responsive to light",
   "Gum Color": "Pink (pale = anemia/shock, yellow = icterus, brick-red = sepsis)",
   "Thoracic Auscultation": "Clear lung sounds bilaterally, no murmur or arrhythmia",
   "Abdominal Palpation": "Non-painful, no masses, no organomegaly",
   "Rectal Temperature Variation": "Slightly elevated with stress or exercise",
   "Urine Specific Gravity": "1.015–1.045 (dog on normal diet)",
   "SPO2": "> 95%",
   "Mean Arterial Pressure": "90–130 mmHg"
 }'::jsonb,
 '["Parvoviral Enteritis", "Gastric Dilatation-Volvulus (GDV / Bloat)", "Hyperadrenocorticism (Cushing''s Syndrome)", "Hypoadrenocorticism (Addison''s Disease)", "Diabetes Mellitus", "Chronic Kidney Disease (CKD)", "Acute Pancreatitis", "Intervertebral Disc Disease (IVDD)", "Hip Dysplasia", "Cruciate Ligament Rupture (CCL)", "Otitis Externa", "Atopic Dermatitis", "Hemangiosarcoma", "Lymphoma", "Osteosarcoma", "Mast Cell Tumor", "Heartworm Disease (Dirofilaria immitis)", "Leptospirosis", "Kennel Cough (CIRD Complex)", "Ehrlichiosis and Anaplasmosis", "Patellar Luxation", "Brachycephalic Obstructive Airway Syndrome (BOAS)"]'::jsonb,
 '{"species_display": "Canine", "years_experience": 8, "specialties": ["emergency", "critical care", "surgery"], "typical_workplace": "small animal referral hospital"}'::jsonb
),

-- ============================================================
-- FELINE NURSE
-- ============================================================
('feline', 'Emily Chen', NULL, 'female', 'shimmer',
 'You are Emily Chen, a specialist feline veterinary nurse with 10 years of experience dedicated exclusively to cat medicine. You are a Certified Feline Friendly Nurse with advanced skills in low-stress handling and feline behavior. You understand that cats are not small dogs — they have unique physiology, metabolism, and disease patterns. You are patient, gentle, and expert at reading feline body language. You communicate findings with precision and advocate for feline-specific approaches.',
 '[
   {"name": "Feline physical examination", "category": "vitals", "description": "Gentle systemic exam respecting feline stress thresholds, body condition scoring (1-9), muscle condition score"},
   {"name": "Feline emergency triage", "category": "procedures", "description": "Urethral obstruction, aortic thromboembolism, dyspnea assessment, status epilepticus"},
   {"name": "Feline anesthesia monitoring", "category": "procedures", "description": "Feline-specific drug protocols, thermoregulation, blood pressure management"},
   {"name": "Feline critical care", "category": "procedures", "description": "IV catheterization (difficult in cats), fluid therapy, nasogastric feeding, blood transfusion"},
   {"name": "Feline blood collection", "category": "lab", "description": "Cephalic, jugular, medial saphenous venipuncture, minimal-stress techniques"},
   {"name": "Feline urinary management", "category": "procedures", "description": "Urethral catheterization, urine collection (cystocentesis), FLUTD management"},
   {"name": "Feline dental procedures", "category": "procedures", "description": "Feline dental charting, FORL detection, stomatitis assessment"},
   {"name": "Feline behavior assessment", "category": "other", "description": "Stress scoring, environmental enrichment, feline-friendly handling"},
   {"name": "Feline nutrition counseling", "category": "other", "description": "Life-stage nutrition, obesity management, hepatic lipidosis prevention"},
   {"name": "Feline geriatric care", "category": "procedures", "description": "Quality of life assessment, chronic disease monitoring, pain scoring"}
 ]'::jsonb,
 '{
   "PCV": "30–45%",
   "Total Protein": "5.7–8.0 g/dL",
   "WBC": "3.5–16.0 × 10⁹/L",
   "Neutrophils": "2.5–12.5 × 10⁹/L",
   "Lymphocytes": "1.0–7.0 × 10⁹/L",
   "Monocytes": "0–0.9 × 10⁹/L",
   "Eosinophils": "0–1.5 × 10⁹/L",
   "Platelets": "180–500 × 10⁹/L",
   "RBC": "5.0–10.0 × 10¹²/L",
   "Hemoglobin": "9–15 g/dL",
   "MCV": "39–55 fL",
   "MCHC": "30–36 g/dL",
   "Sodium": "145–158 mmol/L",
   "Potassium": "3.5–5.5 mmol/L",
   "Chloride": "110–128 mmol/L",
   "Calcium": "2.0–2.7 mmol/L (total)",
   "Phosphorus": "0.9–2.3 mmol/L",
   "Magnesium": "0.7–1.1 mmol/L",
   "Glucose": "3.9–8.3 mmol/L (70–150 mg/dL) — note: stress hyperglycemia common",
   "BUN": "5.0–11.0 mmol/L (14–31 mg/dL)",
   "Creatinine": "70–160 μmol/L (0.8–1.8 mg/dL)",
   "ALT": "12–130 U/L",
   "AST": "10–55 U/L",
   "ALP": "10–80 U/L",
   "GGT": "0–6 U/L",
   "Total Bilirubin": "0–5.1 μmol/L (0–0.3 mg/dL)",
   "Albumin": "25–37 g/L",
   "Cholesterol": "1.7–5.7 mmol/L",
   "Triglycerides": "0.2–1.2 mmol/L",
   "SDMA": "< 18 μg/dL",
   "fPLI": "< 3.5 μg/L (normal)",
   "Total T4": "12–40 nmol/L",
   "fNT-proBNP": "< 100 pmol/L",
   "pH (venous)": "7.31–7.46",
   "Lactate": "< 2.5 mmol/L",
   "Coagulation PT": "8–12 seconds",
   "Coagulation aPTT": "12–20 seconds",
   "Urine Specific Gravity": "> 1.035 typically (concentrating ability)"
 }'::jsonb,
 '{
   "Heart Rate": "120–160 bpm (adult), 200–260 bpm (kitten)",
   "Respiratory Rate": "20–30 breaths/min (at rest), > 40 = concerning",
   "Temperature": "38.0–39.2°C (100.4–102.5°F), stress can elevate to 39.5°C",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist (pale gums = emergency in cats)",
   "Pulse Quality": "Strong, regular, femoral pulse assessment",
   "Hydration Status": "Skin tent < 1 second, moist mucous membranes — cats dehydrate rapidly",
   "Body Condition Score": "1–9 scale, ideal 4–5",
   "Pupil Response": "Bilateral, equal, responsive — note: cats have vertical slit pupils",
   "Gum Color": "Pink, tongue color also important in cats",
   "Thoracic Auscultation": "Heart: murmurs common and significant in cats, sinus arrhythmia is ABNORMAL in cats (unlike dogs)",
   "Abdominal Palpation": "Kidneys palpable, bladder size assessment, cranial abdominal mass check",
   "Feline-Specific Notes": "Stress hyperglycemia up to 20 mmol/L, fructosamine more reliable; cats hide pain — use validated pain scales",
   "Urine Specific Gravity": "> 1.035 (cats concentrate well, < 1.035 is significant)",
   "SPO2": "> 95%",
   "Mean Arterial Pressure": "100–150 mmHg"
 }'::jsonb,
 '["Feline Lower Urinary Tract Disease (FLUTD / FIC)", "Hyperthyroidism", "Chronic Kidney Disease (CKD)", "Feline Leukemia Virus (FeLV)", "Feline Immunodeficiency Virus (FIV)", "Diabetes Mellitus", "Hepatic Lipidosis", "Inflammatory Bowel Disease (IBD)", "Feline Asthma / Bronchitis", "Hypertrophic Cardiomyopathy (HCM)", "Feline Infectious Peritonitis (FIP)", "Feline Panleukopenia", "Upper Respiratory Infection Complex (URI)", "Dental Disease and FORLs", "Feline Acne", "Urethral Obstruction (tom cats)", "Aortic Thromboembolism (saddle thrombus)", "Small Cell Lymphoma", "Squamous Cell Carcinoma", "Feline Hyperesthesia Syndrome"]'::jsonb,
 '{"species_display": "Feline", "years_experience": 10, "specialties": ["feline medicine", "behavior", "critical care"], "typical_workplace": "feline-only practice", "certifications": ["Certified Feline Friendly Nurse"]}'::jsonb
),

-- ============================================================
-- OVINE NURSE
-- ============================================================
('ovine', 'Fiona Murray', NULL, 'female', 'nova',
 'You are Fiona Murray, an experienced ovine veterinary nurse with 14 years of specialisation in sheep health and production. You have extensive experience in extensive hill farming, lowland flocks, and pedigree breeding operations. You are practical, efficient, and understand the economic realities of sheep farming. You communicate findings concisely and are comfortable working in all weather conditions in the field.',
 '[
   {"name": "Ovine physical examination", "category": "vitals", "description": "Systematic exam including body condition scoring (1-5), FAMACHA scoring, locomotion scoring"},
   {"name": "Ovine reproductive management", "category": "procedures", "description": "Pregnancy scanning, lambing assistance, dystocia management, neonatal care"},
   {"name": "Ovine parasitology", "category": "lab", "description": "FEC, larval culture, FAMACHA, fluke detection, anthelmintic resistance testing (FECRT)"},
   {"name": "Ovine flock health programs", "category": "other", "description": "Vaccination protocols, biosecurity, quaratine, replacement selection"},
   {"name": "Ovine nutrition assessment", "category": "other", "description": "Pasture assessment, supplementary feeding, metabolic profiling, trace element monitoring"},
   {"name": "Ovine emergency triage", "category": "procedures", "description": "Hypocalcemia, pregnancy toxaemia, prolapse management, entrapment injuries"},
   {"name": "Ovine lameness evaluation", "category": "procedures", "description": "Foot rot, contagious ovine digital dermatitis (CODD), toe abscess, hoof trimming"},
   {"name": "Ovine surgical assistance", "category": "procedures", "description": "Caesarean section, vasectomy, tail docking, castration"},
   {"name": "Ovine laboratory sample handling", "category": "lab", "description": "Jugular venipuncture, fecal sampling, blood smear, trace element panels"},
   {"name": "Lamb management", "category": "procedures", "description": "Colostrum management, hypothermia treatment, watery mouth prevention, fostering"}
 ]'::jsonb,
 '{
   "PCV": "27–45%",
   "Total Protein": "6.0–7.9 g/dL",
   "WBC": "4.0–12.0 × 10⁹/L",
   "Neutrophils": "0.7–6.0 × 10⁹/L",
   "Lymphocytes": "2.0–7.0 × 10⁹/L",
   "Monocytes": "0–0.5 × 10⁹/L",
   "Eosinophils": "0–1.0 × 10⁹/L",
   "Platelets": "200–600 × 10⁹/L",
   "Fibrinogen": "1–5 g/L",
   "RBC": "8.0–15.0 × 10¹²/L",
   "Hemoglobin": "9–15 g/dL",
   "MCV": "23–35 fL",
   "MCHC": "30–36 g/dL",
   "Sodium": "139–152 mmol/L",
   "Potassium": "3.9–5.4 mmol/L",
   "Chloride": "100–112 mmol/L",
   "Calcium": "2.3–3.0 mmol/L (total)",
   "Phosphorus": "1.3–2.6 mmol/L",
   "Magnesium": "0.7–1.3 mmol/L",
   "Glucose": "2.6–4.4 mmol/L (47–79 mg/dL)",
   "BUN": "2.5–7.1 mmol/L (7–20 mg/dL)",
   "Creatinine": "62–124 μmol/L (0.7–1.4 mg/dL)",
   "AST": "40–120 U/L",
   "CK": "30–200 U/L",
   "GGT": "15–60 U/L (elevated in neonates)",
   "GLDH": "0–10 U/L",
   "Total Bilirubin": "0–5.1 μmol/L",
   "Albumin": "24–37 g/L",
   "Globulin": "30–45 g/L",
   "BHB": "< 0.8 mmol/L (ovine pregnancy toxaemia > 3.0 mmol/L)",
   "NEFA": "< 0.5 mmol/L",
   "Selenium (GSH-Px)": "> 20 U/g Hb",
   "Copper": "9–20 μmol/L",
   "Cobalt (Vitamin B12)": "> 200 pmol/L",
   "Zinc": "12–18 μmol/L",
   "Iodine (serum)": "50–200 nmol/L",
   "pH (venous)": "7.32–7.44",
   "Lactate": "< 2 mmol/L"
 }'::jsonb,
 '{
   "Heart Rate": "70–90 bpm (adult), 100–140 bpm (lamb)",
   "Respiratory Rate": "12–30 breaths/min (adult), 20–40 breaths/min (lamb)",
   "Temperature": "38.5–39.7°C (101.3–103.5°F)",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist — FAMACHA score 1–5 for anaemia assessment",
   "Rumen Motility": "1–2 contractions per minute",
   "Body Condition Score": "1–5 scale, ideal 2.5–3.5 (maintenance), 3.0–3.5 (pre-tupping)",
   "Hydration Status": "Skin tent < 2 seconds, sunken eyes indicate > 5% dehydration",
   "Pulse Quality": "Strong, regular, palpable at femoral artery",
   "Thoracic Auscultation": "Clear lung sounds, no pleural rubs",
   "Abdominal Assessment": "Rumen fill, no bloat, no abdominal pain on ballottement",
   "Locomotion Score": "1–5 scale (1 = sound, 5 = severely lame)",
   "Fecal Consistency": "Pelleted (normal), monitor for scour",
   "Urine pH": "7.0–8.0",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Sheep Scab (Psoroptes ovis)", "Foot Rot (Dichelobacter nodosus)", "Contagious Ovine Digital Dermatitis (CODD)", "Pregnancy Toxaemia (Twin Lamb Disease)", "Hypocalcaemia (Parturient Paresis)", "Ovine Pulmonary Adenocarcinoma (OPA / Jaagsiekte)", "Maedi-Visna Virus (MV)", "Caseous Lymphadenitis (CLA)", "Clostridial Diseases (Pulpy Kidney, Blackleg, Braxy, Tetanus)", "Fasciolosis (Liver Fluke)", "Parasitic Gastroenteritis (Haemonchus, Teladorsagia, Trichostrongylus)", "Coccidiosis", "Toxoplasmosis (Abortion)", "Enzootic Abortion of Ewes (EAE / Chlamydophila)", "Campylobacter Abortion", "Orf (Contagious Pustular Dermatitis)", "Johne''s Disease", "Sheep Pulmonary Adenomatosis", "Listeriosis (Silage eye, neurological form)", "White Muscle Disease (Selenium/Vitamin E deficiency)", "Copper Toxicity", "Watery Mouth (E. coli colibacillosis in lambs)", "Border Disease (Hairy Shaker)", "Scrapie"]'::jsonb,
 '{"species_display": "Ovine", "years_experience": 14, "specialties": ["flock health", "parasitology", "reproduction"], "typical_workplace": "mixed hill and lowland sheep farms"}'::jsonb
),

-- ============================================================
-- CAPRINE NURSE
-- ============================================================
('caprine', 'Rosa Vasquez', NULL, 'female', 'nova',
 'You are Rosa Vasquez, a specialist caprine veterinary nurse with 11 years of experience in dairy goat operations, meat goat herds, and hobby farms. You understand that goats are browsers, not grazers, and have unique metabolism and behavior compared to sheep. You are patient, observant, and skilled at handling even the most stubborn goats. You communicate findings clearly and understand herd health economics.',
 '[
   {"name": "Caprine physical examination", "category": "vitals", "description": "Complete exam including FAMACHA scoring, body condition (1-5), udder assessment, hoof evaluation"},
   {"name": "Caprine reproductive management", "category": "procedures", "description": "Pregnancy diagnosis (US), kidding assistance, dystocia management, CAE prevention"},
   {"name": "Caprine parasitology", "category": "lab", "description": "FEC, FAMACHA, FAMACHA-adapted for goats, Barber pole worm management, FECRT"},
   {"name": "Caprine mastitis management", "category": "procedures", "description": "California Mastitis Test, milk culture, treatment protocols, SCC monitoring"},
   {"name": "Caprine nutrition assessment", "category": "other", "description": "Browse-based diet evaluation, mineral supplementation, metabolic profiling"},
   {"name": "Caprine emergency triage", "category": "procedures", "description": "Pregnancy toxaemia, hypocalcemia, bloat, entrapment injuries, snake bite"},
   {"name": "Caprine lameness evaluation", "category": "procedures", "description": "Foot rot, hoof overgrowth, contagious agalactiae, laminitis"},
   {"name": "Caprine surgical assistance", "category": "procedures", "description": "C-section, disbudding, castration, hernia repair"},
   {"name": "Caprine laboratory sample handling", "category": "lab", "description": "Jugular venipuncture, milk sampling, fecal sampling, skin scrapings"},
   {"name": "Caprine herd health programs", "category": "other", "description": "Vaccination, biosecurity, CAE/CL/Johnes testing, trace mineral monitoring"}
 ]'::jsonb,
 '{
   "PCV": "22–38% (lower than sheep, goats have naturally lower PCV)",
   "Total Protein": "6.0–7.5 g/dL",
   "WBC": "4.0–13.0 × 10⁹/L",
   "Neutrophils": "1.0–7.0 × 10⁹/L",
   "Lymphocytes": "2.0–9.0 × 10⁹/L",
   "Monocytes": "0–0.6 × 10⁹/L",
   "Eosinophils": "0–1.2 × 10⁹/L",
   "Platelets": "200–600 × 10⁹/L",
   "Fibrinogen": "2–5 g/L",
   "RBC": "8.0–15.0 × 10¹²/L",
   "Hemoglobin": "8–14 g/dL",
   "MCV": "19–28 fL",
   "MCHC": "29–35 g/dL",
   "Sodium": "142–155 mmol/L",
   "Potassium": "3.5–5.5 mmol/L",
   "Chloride": "100–115 mmol/L",
   "Calcium": "2.3–3.0 mmol/L",
   "Phosphorus": "1.6–4.5 mmol/L",
   "Magnesium": "0.8–1.4 mmol/L",
   "Glucose": "2.8–4.8 mmol/L (50–86 mg/dL)",
   "BUN": "3.6–10.7 mmol/L (10–30 mg/dL)",
   "Creatinine": "62–124 μmol/L (0.7–1.4 mg/dL)",
   "AST": "40–140 U/L",
   "CK": "30–250 U/L",
   "GGT": "20–60 U/L",
   "GLDH": "0–12 U/L",
   "ALP": "40–150 U/L",
   "Total Bilirubin": "0–5.1 μmol/L",
   "Albumin": "24–37 g/L",
   "BHB": "< 1.0 mmol/L (pregnancy toxaemia > 2.5 mmol/L)",
   "NEFA": "< 0.5 mmol/L",
   "Selenium (GSH-Px)": "> 20 U/g Hb",
   "Copper": "8–20 μmol/L (goats require MORE copper than sheep)",
   "Cobalt (Vitamin B12)": "> 200 pmol/L",
   "Somatic Cell Count": "< 1,000,000 cells/mL (goat milk has naturally higher SCC than cow)",
   "pH (venous)": "7.32–7.44",
   "Lactate": "< 2 mmol/L"
 }'::jsonb,
 '{
   "Heart Rate": "70–100 bpm (adult), 100–150 bpm (kid)",
   "Respiratory Rate": "12–25 breaths/min (adult), 20–40 breaths/min (kid)",
   "Temperature": "38.5–39.7°C (101.3–103.5°F), goats tend to run slightly higher than sheep",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink — FAMACHA scoring applicable",
   "Rumen Motility": "1–2 contractions per minute",
   "Body Condition Score": "1–5 scale, ideal 2.5–3.0 (dairy), 3.0–3.5 (meat)",
   "Hydration Status": "Skin tent < 2 seconds",
   "Pulse Quality": "Strong, regular, femoral artery palpation",
   "Thoracic Auscultation": "Clear lung sounds bilaterally",
   "Abdominal Assessment": "Rumen fill assessment, bloat check (goats prone to frothy bloat on clover)",
   "Udder Assessment": "Soft, no heat or swelling, milk appearance normal",
   "Locomotion Score": "1–5 scale",
   "Fecal Consistency": "Pelleted (normal), goats susceptible to coccidiosis and nematodes",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Caprine Arthritis-Encephalitis (CAE)", "Caseous Lymphadenitis (CL)", "Johne''s Disease", "Pregnancy Toxaemia", "Hypocalcemia (Milk Fever)", "Barber Pole Worm (Haemonchus contortus)", "Coccidiosis", "Caprine Respiratory Complex (Pasteurella, Mycoplasma)", "Contagious Agalactiae (Mycoplasma agalactiae)", "Foot Rot and Scald", "Soremouth (Orf / Contagious Ecthyma)", "Listeriosis", "Polioencephalomalacia (PEM / Thiamine deficiency)", "Enterotoxaemia (Clostridium perfringens Type C&D)", "Tetanus", "Fasciolosis (Liver Fluke)", "Caprine Abortion Complex (Toxoplasma, Chlamydia, Coxiella, Leptospira)", "Mastitis (Staph, Strept, Mycoplasma)", "Urinary Calculi (especially in wethers)", "White Muscle Disease (Selenium deficiency)", "Copper Toxicity (less susceptible than sheep but possible), Copper Deficiency (more common in goats than sheep)", "Floppy Kid Syndrome", "Bloat (frothy and free-gas)"]'::jsonb,
 '{"species_display": "Caprine", "years_experience": 11, "specialties": ["dairy goat production", "parasitology", "herd health"], "typical_workplace": "dairy goat operations and smallholdings"}'::jsonb
),

-- ============================================================
-- PORCINE NURSE
-- ============================================================
('porcine', 'Henrik Sorensen', NULL, 'male', 'echo',
 'You are Henrik Sorensen, a skilled porcine veterinary nurse with 13 years of experience in commercial pig production, including farrow-to-finish, wean-to-finish, and nucleus breeding herds. You are detail-oriented, understand production metrics deeply, and are proficient in herd-level diagnostics. You communicate findings efficiently and understand the strict biosecurity requirements of modern pig farming.',
 '[
   {"name": "Porcine physical examination", "category": "vitals", "description": "Individual and pen-level assessment, body condition scoring (1-5), lameness scoring"},
   {"name": "Porcine reproductive management", "category": "procedures", "description": "Farrowing supervision, neonatal care, AI assistance, estrus detection, weaning protocols"},
   {"name": "Porcine herd health programs", "category": "other", "description": "Vaccination protocols, all-in/all-out management, biosecurity, gilt development"},
   {"name": "Porcine emergency triage", "category": "procedures", "description": "Farrowing complications, piglet crushing, hernia strangulation, heat stress"},
   {"name": "Porcine nutrition assessment", "category": "other", "description": "Phase feeding, gilt/sow body condition, creep feeding, water intake monitoring"},
   {"name": "Porcine respiratory evaluation", "category": "procedures", "description": "Cough scoring, thoracic auscultation, pleurisy assessment at slaughter"},
   {"name": "Porcine surgical assistance", "category": "procedures", "description": "Castration, tail docking, teeth clipping, hernia repair, C-section"},
   {"name": "Porcine laboratory sample handling", "category": "lab", "description": "Ear vein, cranial vena cava, tail vein sampling, oral fluids, processing fluids"},
   {"name": "Porcine necropsy assistance", "category": "procedures", "description": "Systematic post-mortem examination, lesion scoring, sample collection for histopathology"},
   {"name": "Porcine welfare assessment", "category": "other", "description": "Tail biting risk assessment, enrichment evaluation, lameness scoring, body condition"}
 ]'::jsonb,
 '{
   "PCV": "32–45%",
   "Total Protein": "6.0–8.5 g/dL",
   "WBC": "10.0–22.0 × 10⁹/L (higher than ruminants)",
   "Neutrophils": "3.0–13.0 × 10⁹/L",
   "Lymphocytes": "5.0–13.0 × 10⁹/L (lymphocyte-dominant, unlike ruminants)",
   "Monocytes": "0–1.5 × 10⁹/L",
   "Eosinophils": "0–1.5 × 10⁹/L",
   "Platelets": "200–500 × 10⁹/L",
   "RBC": "5.0–8.0 × 10¹²/L",
   "Hemoglobin": "10–16 g/dL",
   "MCV": "50–68 fL",
   "MCHC": "30–36 g/dL",
   "Sodium": "135–150 mmol/L",
   "Potassium": "4.0–6.0 mmol/L",
   "Chloride": "95–108 mmol/L",
   "Calcium": "2.1–2.8 mmol/L",
   "Phosphorus": "1.7–3.3 mmol/L (higher in growing pigs)",
   "Magnesium": "0.8–1.3 mmol/L",
   "Glucose": "3.9–6.4 mmol/L (70–115 mg/dL)",
   "BUN": "2.1–7.1 mmol/L (6–20 mg/dL)",
   "Creatinine": "88–137 μmol/L (1.0–1.5 mg/dL)",
   "ALT": "20–55 U/L",
   "AST": "15–55 U/L",
   "GGT": "20–60 U/L",
   "ALP": "40–140 U/L (higher in growing pigs)",
   "Total Bilirubin": "0–5.1 μmol/L",
   "Albumin": "25–40 g/L",
   "Total Protein": "6.0–8.5 g/dL",
   "Triglycerides": "0.2–0.8 mmol/L",
   "pH (venous)": "7.35–7.45",
   "Lactate": "< 2 mmol/L",
   "Fibrinogen": "1–4 g/L"
 }'::jsonb,
 '{
   "Heart Rate": "60–90 bpm (adult sow), 100–130 bpm (piglet)",
   "Respiratory Rate": "15–25 breaths/min (adult at rest), cough scoring: 0–3 scale",
   "Temperature": "38.6–39.7°C (101.5–103.5°F), piglets prefer 30–34°C environment",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist",
   "Body Condition Score": "1–5 scale, ideal 3.0 (sow at farrowing), monitor closely in lactation",
   "Hydration Status": "Skin tent < 2 seconds, water intake 10–25 L/day (lactating sow)",
   "Pulse Quality": "Strong, regular, ear vein assessment",
   "Thoracic Auscultation": "Clear lung sounds, no crackles or wheezes, cough index per 100 pigs",
   "Abdominal Assessment": "Rectal palpation if needed, distension check, bowel sounds present",
   "Locomotion Score": "0–4 scale (0 = normal, 4 = non-ambulatory), common issue in sows",
   "Skin Assessment": "No erythema, no necrosis, no melanomas, mange scoring",
   "Reproductive Status": "Gestation ~115 days, weaning at 21–28 days, return to estrus 4–7 days post-weaning",
   "Fecal Consistency": "Formed to soft (adults), monitor for diarrhea especially post-weaning",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Porcine Reproductive and Respiratory Syndrome (PRRS)", "Swine Influenza", "Porcine Circovirus Type 2 (PCV2 / PDNS / PMWS)", "Mycoplasma hyopneumoniae (Enzootic Pneumonia)", "Actinobacillus pleuropneumoniae (APP)", "Streptococcus suis", "Haemophilus parasuis (Glasser''s Disease)", "Escherichia coli (Edema Disease, Post-weaning Diarrhea, Neonatal Scours)", "Swine Dysentery (Brachyspira hyodysenteriae)", "Lawsonia intracellularis (PIA / Ileitis)", "African Swine Fever (ASF)", "Classical Swine Fever (Hog Cholera)", "Foot and Mouth Disease", "Porcine Parvovirus (PPV)", "Leptospirosis", "Erysipelas", "Clostridial Infections (C. perfringens Type C, C. difficile)", "Mange (Sarcoptes scabiei)", "Tail Biting Complex", "Rectal Stricture / Prolapse", "Sow Mastitis-Metritis-Agalactia (MMA) Complex", "Cystic Ovarian Degeneration", "Zinc Deficiency (Parakeratosis)", "Vitamin E/Selenium Deficiency (Mulberry Heart Disease, Hepatosis Dietetica)"]'::jsonb,
 '{"species_display": "Porcine", "years_experience": 13, "specialties": ["commercial pig production", "herd health", "biosecurity"], "typical_workplace": "commercial farrow-to-finish and wean-to-finish units"}'::jsonb
),

-- ============================================================
-- CAMELID NURSE
-- ============================================================
('camelid', 'Dr. Ana Mendoza', NULL, 'female', 'shimmer',
 'You are Ana Mendoza, a veterinary nurse specialising in South American camelids with 9 years of experience in alpaca, llama, and camel medicine. You understand the unique physiology of camelids — their three-chambered stomach, tendency to mask illness, unique reproductive cycle (induced ovulators), and susceptibility to heat stress. You are patient with these often-nervous animals and skilled at gentle restraint techniques. You communicate findings precisely.',
 '[
   {"name": "Camelid physical examination", "category": "vitals", "description": "Gentle examination respecting flight response, body condition scoring (1-10), fiber assessment"},
   {"name": "Camelid reproductive management", "category": "procedures", "description": "Induced ovulation protocols, pregnancy diagnosis (US), cria management, dystocia"},
   {"name": "Camelid emergency triage", "category": "procedures", "description": "Heat stress, choke, colic, snake bite, neurologic disease (meningeal worm)"},
   {"name": "Camelid parasitology", "category": "lab", "description": "FEC, meningeal worm surveillance, whipworm detection, coccidia, liver fluke"},
   {"name": "Camelid nutrition assessment", "category": "other", "description": "Forage-based diet evaluation, selenium/vitamin E monitoring, copper sensitivity awareness"},
   {"name": "Camelid fiber assessment", "category": "other", "description": "Fiber diameter evaluation, shearing assistance, skin biopsy (show animals)"},
   {"name": "Camelid surgical assistance", "category": "procedures", "description": "Castration (older animals require surgical technique), cesarean section, teeth trimming"},
   {"name": "Camelid laboratory sample handling", "category": "lab", "description": "Jugular venipuncture (large vessel), ear vein, cria venipuncture challenges"},
   {"name": "Camelid neonatal care", "category": "procedures", "description": "Cria assessment, IgG passive transfer testing, hypothermia management, bottle feeding"},
   {"name": "Camelid behavior and handling", "category": "other", "description": "Gentle restraint, chute training, herd dynamics assessment, stress minimization"}
 ]'::jsonb,
 '{
   "PCV": "28–42%",
   "Total Protein": "5.5–7.5 g/dL",
   "WBC": "6.0–17.0 × 10⁹/L",
   "Neutrophils": "3.0–11.0 × 10⁹/L",
   "Lymphocytes": "1.5–6.0 × 10⁹/L",
   "Monocytes": "0–0.8 × 10⁹/L",
   "Eosinophils": "0–2.5 × 10⁹/L (often elevated with parasitism)",
   "Platelets": "150–450 × 10⁹/L",
   "RBC": "8.0–14.5 × 10¹²/L (high RBC count is normal — high altitude adaptation)",
   "Hemoglobin": "10–16 g/dL",
   "MCV": "22–30 fL (small RBCs — unique to camelids)",
   "MCHC": "32–38 g/dL (slightly high — camelid RBCs are elliptical, not round)",
   "Sodium": "142–155 mmol/L",
   "Potassium": "3.8–5.6 mmol/L",
   "Chloride": "100–115 mmol/L",
   "Calcium": "2.3–3.0 mmol/L",
   "Phosphorus": "1.3–2.8 mmol/L",
   "Magnesium": "0.7–1.2 mmol/L",
   "Glucose": "3.3–7.2 mmol/L (60–130 mg/dL) — stress hyperglycemia common",
   "BUN": "3.6–12.1 mmol/L (10–34 mg/dL)",
   "Creatinine": "106–177 μmol/L (1.2–2.0 mg/dL) — higher baseline than other species",
   "ALT": "10–40 U/L",
   "AST": "10–80 U/L",
   "GGT": "10–50 U/L",
   "ALP": "20–120 U/L",
   "Total Bilirubin": "0–5.1 μmol/L",
   "Albumin": "25–38 g/L",
   "SDMA": "< 18 μg/dL",
   "Selenium (whole blood)": "> 0.08 μg/mL",
   "Vitamin E (serum)": "> 2 μg/mL",
   "Copper": "0.5–1.2 μg/mL (camelids VERY sensitive to copper toxicity — keep lower than sheep/goats)",
   "Vitamin D": "> 20 nmol/L (critical for growing crias, deficiency → rickets)",
   "pH (venous)": "7.32–7.44",
   "Lactate": "< 2.5 mmol/L",
   "IgG (cria)": "> 800 mg/dL (adequate passive transfer), < 800 = failure of passive transfer"
 }'::jsonb,
 '{
   "Heart Rate": "60–90 bpm (adult), 100–140 bpm (cria)",
   "Respiratory Rate": "10–30 breaths/min (adult), 20–40 breaths/min (cria)",
   "Temperature": "37.5–38.9°C (99.5–102.0°F) — camelids tend to run lower than other livestock",
   "Capillary Refill Time": "< 2 seconds",
   "Mucous Membranes": "Pink, moist — check for anemia (barber pole worm), icterus (liver fluke)",
   "Rumen Motility": "First compartment (C1) contractions, 3–4 per minute, auscultate left flank",
   "Body Condition Score": "1–10 scale (1 = emaciated, 10 = obese), ideal 5–6, palpate lumbar region",
   "Hydration Status": "Skin tent < 2 seconds, sunken eyes significant in camelids",
   "Pulse Quality": "Strong, regular, femoral artery",
   "Thoracic Auscultation": "Heart and lungs, check for murmurs (common in older camelids)",
   "Abdominal Assessment": "C1 fill, no distension, camelids prone to fatal colic",
   "Fiber Assessment": "Clean, no matting, no evidence of external parasites",
   "Fecal Consistency": "Pelleted, similar to sheep/goats, monitor for diarrhea",
   "Heat Stress Assessment": "Rectal temp > 39.5°C = concerning, > 40°C = emergency",
   "Behavioral Notes": "Sternal recumbency (kusma) is normal resting posture, not a sign of illness",
   "SPO2": "> 95%"
 }'::jsonb,
 '["Meningeal Worm (Parelaphostrongylus tenuis) — CRITICAL in North America", "Haemonchosis (Barber Pole Worm)", "Eimeria (Coccidiosis)", "Facial Eczema (Pithomices chartarum spores)", "Rickets (Vitamin D deficiency in crias)", "Heat Stress / Hyperthermia", "Choke (Esophageal obstruction)", "Colic (First compartment impaction, fermentative colic)", "Coronavirus (Cria diarrhea)", "BVDV Persistent Infection (Bovine Viral Diarrhea Virus crosses species)", "Mycoplasma haemolamae", "Liver Fluke (Fasciola hepatica)", "Tuberculosis (M. bovis)", "Selenium/Vitamin E Deficiency (White Muscle Disease)", "Copper Toxicity (camelids highly susceptible)", "Toxic Plant Ingestion (Rhododendron, Oleander, Azalea)", "Uterine Torsion", "Failure of Passive Transfer (FPT in crias)", "Mastitis", "Caseous Lymphadenitis (CL)", "Dermatophytosis (Ringworm)", "Sarcoptic Mange"]'::jsonb,
 '{"species_display": "Camelid (Alpaca/Llama)", "years_experience": 9, "specialties": ["camelid medicine", "reproduction", "neonatal care"], "typical_workplace": "alpaca and llama breeding farms"}'::jsonb
),

-- ============================================================
-- AVIAN NURSE
-- ============================================================
('avian', 'Dr. Priya Sharma', NULL, 'female', 'shimmer',
 'You are Priya Sharma, an avian veterinary nurse with 10 years of experience in poultry production, backyard flocks, and companion birds. You have worked with commercial layers, broilers, turkeys, and game birds. You understand avian anatomy and physiology is fundamentally different from mammals — air sacs, hollow bones, no diaphragm, cloaca, and unique respiratory and digestive systems. You are methodical in flock-level investigation and skilled at individual bird examination.',
 '[
   {"name": "Avian physical examination", "category": "vitals", "description": "Restraint techniques, body condition, crop assessment, keel scoring, plumage evaluation"},
   {"name": "Avian emergency triage", "category": "procedures", "description": "Egg-bound, respiratory distress, prolapse, heat stress, trauma"},
   {"name": "Avian necropsy technique", "category": "procedures", "description": "Systematic post-mortem, lesion scoring, sample collection for histopathology and bacteriology"},
   {"name": "Poultry flock health investigation", "category": "other", "description": "Production metrics analysis, mortality pattern review, litter assessment, water line check"},
   {"name": "Avian parasitology", "category": "lab", "description": "Fecal floatation, coccidia oocyst counting, worm burden assessment, red mite detection"},
   {"name": "Avian laboratory sample handling", "category": "lab", "description": "Wing vein (brachial), jugular, medial metatarsal venipuncture, blood smear evaluation"},
   {"name": "Avian respiratory evaluation", "category": "procedures", "description": "Auscultation, tracheal examination, air sac assessment, sinus flush"},
   {"name": "Avian nutrition assessment", "category": "other", "description": "Feed analysis, calcium/phosphorus balance, vitamin supplementation, Gizzard erosion scoring"},
   {"name": "Avian vaccination programs", "category": "other", "description": "Hatchery vaccination, drinking water, spray, injection protocols"},
   {"name": "Avian biosecurity", "category": "other", "description": "Disease prevention, quarantine protocols, disinfection, wild bird exclusion"}
 ]'::jsonb,
 '{
   "PCV": "25–45% (varies by species, lower in layers during production)",
   "Total Protein": "3.0–5.5 g/dL (lower than mammals)",
   "WBC": "8.0–30.0 × 10⁹/L (heterophils dominant, NOT neutrophils — birds lack neutrophils)",
   "Heterophils": "2.0–12.0 × 10⁹/L",
   "Lymphocytes": "3.0–15.0 × 10⁹/L",
   "Monocytes": "0–2.0 × 10⁹/L",
   "Eosinophils": "0–1.0 × 10⁹/L",
   "Basophils": "0–1.5 × 10⁹/L",
   "Platelets": "Thrombocytes: 20–60 × 10⁹/L (birds have thrombocytes, not platelets)",
   "RBC": "2.0–4.0 × 10¹²/L (nucleated RBCs — unique to birds)",
   "Hemoglobin": "8–16 g/dL",
   "MCV": "90–140 fL (larger, nucleated RBCs)",
   "MCHC": "28–36 g/dL",
   "Sodium": "140–155 mmol/L",
   "Potassium": "3.0–5.5 mmol/L",
   "Chloride": "100–118 mmol/L",
   "Calcium": "2.1–2.8 mmol/L (non-laying); 4.0–8.0 mmol/L (in lay — highly elevated is NORMAL)",
   "Phosphorus": "1.3–3.5 mmol/L",
   "Glucose": "10.0–16.7 mmol/L (180–300 mg/dL) — birds have HIGHER glucose than mammals",
   "BUN": "0.5–2.5 mmol/L (2–7 mg/dL) — birds have LOW BUN, uric acid is primary nitrogenous waste",
   "Uric Acid": "120–420 μmol/L (2.0–7.0 mg/dL) — PRIMARY kidney marker in birds (not creatinine)",
   "AST": "130–350 U/L (also found in muscle — not liver-specific)",
   "ALT": "10–40 U/L (less useful than in mammals)",
   "Bile Acids": "15–45 μmol/L (best liver function test in birds)",
   "ALP": "40–200 U/L",
   "CK": "100–500 U/L (elevated with muscle damage or handling stress)",
   "Total Bilirubin": "Birds do NOT produce bilirubin — icterus is NOT a clinical sign",
   "Albumin": "10–22 g/L (lower than mammals)",
   "Globulin": "15–30 g/L",
   "Total Protein (in lay)": "May drop to 3.0 g/dL due to estrogen-induced hyperproteinemia — normals differ",
   "pH (venous)": "7.35–7.45",
   "pCO2 (venous)": "25–35 mmHg (birds have efficient gas exchange — lower pCO2)",
   "Lactate": "< 3 mmol/L"
 }'::jsonb,
 '{
   "Heart Rate": "250–400 bpm (chicken), varies greatly by species size",
   "Respiratory Rate": "15–30 breaths/min (chicken at rest) — birds have NO diaphragm, rely on air sacs",
   "Temperature": "40.5–42.0°C (105.0–107.5°F) — birds have HIGHER body temperature than mammals",
   "Capillary Refill Time": "< 2 seconds (less reliable in birds, check mucous membrane color)",
   "Mucous Membranes": "Pink, moist — check choanal slit and infraorbital sinus",
   "Crop Assessment": "Should empty in 4–6 hours, impacted crop = emergency",
   "Keel Score": "1–3 scale (1 = prominent keel/thin, 2 = moderate, 3 = well-covered)",
   "Hydration Status": "Skin tent unreliable — assess mucous membranes, crop fill, vent moistness",
   "Pulse Quality": "Peripheral pulses difficult to assess, monitor heart rate via auscultation",
   "Thoracic Auscultation": "Air sacs auscultated in axillary and caudal abdominal regions",
   "Abdominal Assessment": "Palpate for egg-bound, ascites, tumor; vent examination for prolapse",
   "Plumage Assessment": "Clean, complete, no feather loss or damage, preen gland intact",
   "Fecal Assessment": "Normal: brown-gray firm with white urate cap; cecal droppings: darker, pasty (normal intermittently)",
   "Respiratory Signs": "Open-mouth breathing, tail bobbing, audible respiratory noise = significant",
   "Comb and Wattles": "Red and turgid (normal in healthy hen), pale = anemia/shock, purple = cyanosis",
   "SPO2": "> 95% (less commonly used in avian practice)"
 }'::jsonb,
 '["Avian Influenza (HPAI / LPAI)", "Newcastle Disease (Paramyxovirus)", "Infectious Bronchitis (IBV)", "Marek''s Disease", "Infectious Bursal Disease (IBD / Gumboro)", "Coccidiosis (Eimeria spp.)", "Fowl Pox", "Infectious Laryngotracheitis (ILT)", "Mycoplasma gallisepticum (CRD)", "E. coli Colibacillosis", "Salmonellosis (S. pullorum, S. gallinarum, S. enteritidis)", "Necrotic Enteritis (Clostridium perfringens)", "Histomoniasis (Blackhead Disease)", "Aspergillosis", "Red Mite (Dermanyssus gallinae)", "Egg Peritonitis / Salpingitis", "Egg-bound (Dystocia)", "Prolapsed Vent / Cloacal Prolapse", "Fatty Liver Hemorrhagic Syndrome", "Ascites Syndrome (Pulmonary Hypertension)", "Sudden Death Syndrome (Flip-over)", "Cannibalism / Feather Pecking Complex", "Gout (Visceral and Articular)", "Vitamin E/Selenium Deficiency (Exudative Diathesis)", "Botulism"]'::jsonb,
 '{"species_display": "Avian", "years_experience": 10, "specialties": ["poultry production medicine", "flock health investigation", "avian clinical pathology"], "typical_workplace": "commercial poultry units and backyard flocks"}'::jsonb
)

ON CONFLICT (species_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  behavior_prompt = EXCLUDED.behavior_prompt,
  skills = EXCLUDED.skills,
  lab_reference_ranges = EXCLUDED.lab_reference_ranges,
  vital_reference_ranges = EXCLUDED.vital_reference_ranges,
  common_pathologies = EXCLUDED.common_pathologies,
  metadata = EXCLUDED.metadata,
  updated_at = now();
